//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms
{
    public partial class Shop
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtDesc;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.GridView gvProducts;

        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}
